---
- name: Converge
  hosts: all
  include_vars:
    name: "vagrant_hosts.yml"
  roles:
    - { role: vagrant_manage_hosts, taskname: "create_config_file"}
    - { role: vagrant_manage_hosts, taskname: "create_vagrantfile"}

  tasks:
    - name: Display generated files
      include_tasks: "display_files.yml"
      with_items: "{{ vagrant_vm_list }}"
...
